### ISSUE TITLE
autoproj2.0: autoproj does not install optional dependancies

### ISSUE THREAD

**Issue by goldhoorn** [rock-core/autoproj#101]
I have set:
https://github.com/goldhoorn/buildconf/blob/master/init.rb#L31

but autoproj does not install the clang osdeps.
if i call autoproj show typelib it is still listed as optional dependency but calling autoproj osdeps does not install it

https://github.com/orocos-toolchain/autoproj/blob/master/orocos.autobuild#L73

(but the gccxml dependency is not displayed)

**Comment by doudou** [comment]
It is probably due to a change in the way autoproj handles the environment (in summary: not changing ENV directly anymore)

The "right" way in autoproj 2.0 is to access Autoproj.workspace.env[] for global environment variables. [I've made a 1.9+2.0-compatible fix for the clang/castxml selection here](https://github.com/orocos-toolchain/autoproj/blob/castxml/orocos.autobuild#L76)

**Comment by doudou** [comment]
Fixed by https://github.com/orocos-toolchain/autoproj/pull/16
