### ISSUE TITLE
autoproj2.0.0.rc15: my_project/.autoproj/env.sh is missing

### ISSUE THREAD

**Issue by D-Alex** [rock-core/autoproj#107]
after an autoproj upgrade autoproj is adding a line to the env.sh which is referring to my_project/.autoproj/env.sh which does not exist.

workaround:

     touch .autoproj/env.sh

**Comment by doudou** [comment]
Could you try using autoproj_install to upgrade ? "upgrade" is an artifact that I am removing anyways.

**Comment by doudou** [comment]
Reference: https://www.mail-archive.com/rock-dev@dfki.de/msg01810.html

**Comment by D-Alex** [comment]
Thx, for the link. I will try on the next machine. However, the install script is a bit non standard. Maybe the following workflow is a bit cleaner.

     gem install autoproj
     autoproj 
      --> you are using an old workspace layout. Do you want to upgrade?
      --> if you do not want to upgrade 'call gem remove XXXX and install version YYYYY

This handles a lot of use cases like:
* someone installed autoproj as a global gem
* someone called gem install autoproj to upgrade because there is a newer version on the web which is not picked up (no self upgrade to v2)

**Comment by D-Alex** [comment]
another issue wich might be related not using the install script:

cannot load Hoe gem in case of using rake. The reason is that there is a rake bin located in .autoproj/autoproj/bin/rake which uses only the gemfile in .autoproj/autoproj leaving the one out located in install/gems. The rake bin was auto generated by bundler at least this is written on the top.

removing .autoproj/autoproj/bin/rake solves this issue and the one from install/gems/bin/ is automatically being used.

**Comment by doudou** [comment]
> The rake bin was auto generated by bundler at least this is written on the top.

Yes, got it that one. The workaround is indeed to remove the rake script. Autoproj is supposed to do it but somehow does not.

I unfortunately do not have much time to iron out all these problems right now ... apologies.

**Comment by doudou** [comment]
> Maybe the following workflow is a bit cleaner.

It looks like it is. But it's not, because it relies on the user knowing how to manage its gem environment properly. Autoproj has quite a bit of dependencies (whether it's for good or bad reasons is a different story...), which makes it hard. The very first autoproj versions allowed people to play with the gem environment and it was the single biggest source of errors on install.

The only global dependency on the install process is now bundler, which is *designed* for this purpose (it has zero dependencies, and it's still compatible with 1.8.7)

**Comment by doudou** [comment]
This should be fixed by the way.
