### ISSUE TITLE
Autoproj 2: Order of ENV checks/sets

### ISSUE THREAD

**Issue by jmachowinski** [rock-core/autoproj#115]
We have the setup, that we disable the cross flavor checks in our
init.rb : 
Autobuild.env_set 'ROCK_DISABLE_CROSS_FLAVOR_CHECKS', '1'

This is not realized in the check in rock.core in 
overrides.rb:
if ENV['ROCK_DISABLE_CROSS_FLAVOR_CHECKS'] != '1'

Is this just a bug, or do we set the variable in the wrong place ?
Generation of envsh also fails because of this.

**Comment by doudou** [comment]
Autoproj 2.0's environment handling has significantly changed. ENV does not get updated anymore as the environment is generated per-package (and globally, once, for the env.sh). It was originally using an environment variable because it was meant to be set from the shell.

Just set the environment explicitely in init.rb
  ENV['ROCK_DISABLE_CROSS_FLAVOR_CHECKS'] = '1'
