### ISSUE TITLE
Missing add_build_system_dependency function

### ISSUE THREAD

**Issue by hemker** [rock-core/autoproj#117]
Since commit 0b82d3418051e9883f63423867635bad63e756f4 "cli: make autoproj-update a seperate tool", the function add_build_system_dependency is missing. Is there any equivalent method?

**Comment by doudou** [comment]
Nope. This was a method that was really a hack that stopped being needed a long time ago.

Could you provide me with your use case ? It would help either tell you how to modify it, or help me understand why it should be re-added.

**Comment by hemker** [comment]
From the DFKI compiler speedup package set, you can allow autoproj to download and configure ccache and icecc to provide distributed compiling. This selection is realised as an add_build_system_dependency using command line option when bootstrapping.

**Comment by doudou** [comment]
For this one, you can achieve the same by either:

1. forcing the install of the package in the autobuild file (will have to be guarded with respond_to? tests for backward v1 compatibility)
  `Autoproj.workspace.install_os_packages(['ccache', 'icecc'])
2. adding the dependency to the cmake / autotools packages. Look in rock.core's overrides.rb which iterates over all packages and does stuff to them (is backward compatible)

(2) is better because it won't attempt to install the packages if they're not needed.

**Comment by hemker** [comment]
I don't know how to add the osdeps dependency to packages like mentioned in method (2), since there aren't any concrete packages in the compilerspeedup pkgset (no *.autobuild etc.)

**Comment by doudou** [comment]
a package set's `overrides.rb` file is executed after all the autobuild files got loaded (from all package sets). You can iterate over all existing packages with something like https://github.com/rock-core/package_set/blob/master/overrides.rb#L70 and then check on the package type. Something like

```
Autoproj.manifest.each_autobuild_package do |pkg|
    case pkg
    when Autobuild::CMake, Autobuild::Autotools
         pkg.depends_on 'stuff'
    end
end
```

**Comment by hemker** [comment]
That solution works, but how can I make sure that the command

```ruby
if (Autoproj.user_config('ccacheSize')) then
        cmd = "ccache -M #{Autoproj.user_config('ccacheSize')} > /dev/null"
        system(cmd)
end
```

is executed _after_ the resolved installation dependency of ccache? Referencing this option in an environment such as pkg.post_install results in making this option not reconfigurable...

**Comment by doudou** [comment]
Unrelated comment first:

Do not run system(string). In any language. Always find which command in the language allows you to specify the arguments separately. In ruby, that would be:

```
system('ccache', '-M', Autoproj.config.get('ccacheSize').to_s, out: '/dev/null')
```

and always check the returned value of what you're shelling out to (system returns false on non-zero exit code)

**Comment by doudou** [comment]
Now, for the actual problem: this indeed won't work. Unfortunately, post_import won't help and post_install, as you noticed, is too late.

**Comment by hemker** [comment]
So what to do now? Maybe get back the add_build_system_dependency method?

**Comment by doudou** [comment]
> So what to do now?

Dig deeper. The ccache configuration case you showed me looked suspicious to me, so I looked in v1's implementation of add_build_system_dependency

Unless I'm missing something (which is very well possible given how horrible v1 general organization was horrible), there is no functional difference between add_build_system_dependency and what I asked you to do. Basically, the ccache setup shelling-out you probably fails on autoproj v1 (silently, since you did not check for its output) on the first bootstrap, and worked in following calls because ccache was then setup.

It would have gone unnoticed because it would "work" when one does the `autoproj update` first (ccache setup fails, ccache gets installed) and then `autoproj build` sequence (the 'build' would configure ccache properly)

**Comment by hemker** [comment]
works now!

**Comment by doudou** [comment]
> works now!

Changed anything ?

**Comment by hemker** [comment]
Not in autoproj. Made use of the autoproj update/build hook solution
