### ISSUE TITLE
autoproj rebuild gem pristine fail

### ISSUE THREAD

**Issue by leifole** [rock-core/autoproj#118]
Hi,

when doing an autoproj (v1.13.5) rebuild, the osdeps phase fails calling gem pristine. This is only the case, if you have the same gem installed in your rock environment and on the system. The gem pristine call seems to try to write to /usr/share/rubygems-integration, where it has no rights to do so.

**Comment by doudou** [comment]
Damn I checked that bug and realized that there were already measures to work around this rubygem bug ... and there was :(

As you stated yourself, it happens if a gem is being used by the autoproj install, but the corresponding Ubuntu package is installed on the system anyways. Autoproj will then call `gem pristine GEM_NAME` which will attempt to restore both the 'real gem' and the ubuntu package. And fail.

Anyways, the only solution I see at this stage is to *not* restore the gem to pristine condition. This would impact someone that would try to change a ruby interpreter on an already bootstrapped install (as e.g. when updating the underlying OS). This is not very well supported anyways, so ...

Thoughts ?

**Comment by doudou** [comment]
Given the lack of following-up from both our sides, and the release of v2, I'm closing this
