### ISSUE TITLE
Autoproj uses only 6 threads on Ryzen 5 1700

### ISSUE THREAD

**Issue by jmachowinski** [rock-core/autoproj#134]
By default autoproj uses 6 cores on my Ryzen 5 1700,
while the processor got 12 threads. Is this wanted
behaviour or a bug ?

**Comment by doudou** [comment]
Yes. Because once you use SMT other people complain that it should not and only use real cores.

Moreover, there's the problem of memory (Rock/GCC needed at some point ~1G per thread on the worst parts)

In any case, you can override it by editing `~/.autoprojrc` and add `Autobuild.parallel_build_level = 16`

**Comment by jmachowinski** [comment]
The option is not picked up from the .autoprojrc
entering is in the init.rb works as expected

**Comment by doudou** [comment]
My bad. On v2 it became a configuration option. `Autoproj.config.parallel_build_level = 16`
