### ISSUE TITLE
bundler 2.1.0 breaks rock-core compilation and runtime

### ISSUE THREAD

**Issue by gabrielfpacheco** [rock-core/autoproj#297]
rock-basics tutorial fails to compile (amake):
```
2019-12-17 14:16:21 -0300: running
    cmake .
in directory /home/pacheco/dev/rock-basics/base/types/build
-- Export include dir: '/home/pacheco/dev/rock-basics/base/types/build/include/_base-geometry_/base/geometry' already exists
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   system
-- Export include dir: '/home/pacheco/dev/rock-basics/base/types/build/include/_base_/base' already exists
-- SISL found: /home/pacheco/dev/rock-basics/install/lib/libsisl.so
-- vizkit3d found ... building the vizkit3d plugin
-- Export include dir: '/home/pacheco/dev/rock-basics/base/types/build/include/_vizkit3d_/vizkit3d' already exists
-- FindRuby: looking for config.h
-- did not find Yard, the Ruby packages won't generate documentation
-- Ruby library found: /usr/lib/x86_64-linux-gnu/libruby-2.5.so
-- found Ruby version 2.5.1
-- Using rice library: 
pkg-config: /home/pacheco/dev/rock-basics/base/types/bindings/ruby/base_types_ruby.pc.in is not available for configuration
-- Ruby extension installation dir: lib/x86_64-linux-gnu/ruby/2.5.0
-- unit tests disabled as ROCK_TEST_ENABLED is set to OFF
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pacheco/dev/rock-basics/base/types/build
Exit: pid 17975 exit 0
```
I tried to debug FindGem.cmake (in base/cmake) looking at GEM_LOCAL_INFO and GEM_RUN_RESULT.
GEM_RUN_RESULT outputs "0" and GEM_LOCAL_INFO outputs "" (empty).
When running cmake (not amake) I got the right paths in GEM_LOCAL_INFO
(.../rice/...)

I am getting this error after the new bundler release (2.1.0).

**Comment by doudou** [comment]
> I am getting this error after the new bundler release (2.1.0).

This is indeed a problem due to bundler. I've notified the rock-dev mailing list but forgot to add an issue on GitHub.

Unfortunately, Autoproj does not have support to pin the bundler version (well, I just implemented that today, given ...). The Bundler developers have already fixed it, but they say they will release the bugfix release tomorrow or the day after tomorrow.

One solution would be to package bundler's git manually and install it, if you know how to do that.

I apologize for the trouble this causes. As I just told you, I'm learning my lesson and the next version of autoproj will allow one to select the bundler version to use, which will make sure people can continue working if another bug like this happens.

**Comment by doudou** [comment]
For reference:

- bundler bug: https://github.com/bundler/bundler/issues/7490
- autoproj support to select the bundler version: https://github.com/rock-core/autoproj/pull/298

**Comment by gabrielfpacheco** [comment]
Thank you for looking into it! 

I was able to successfully use the new version of autoproj that supports bundler version selection (#298) until we get the bugfix release from bundler.

**Comment by doudou** [comment]
2.1.1 has been released overnight... CI is green again.
