### ISSUE TITLE
Pass (additional) index url to pip install command

### ISSUE THREAD

**Issue by moooeeeep** [rock-core/autoproj#398]
The [PipManager](https://github.com/rock-core/autoproj/blob/master/lib/autoproj/package_managers/pip_manager.rb) currently installs all pip osdeps in one big install command. It can only install from the default package index, and allows besides the version range spec that can be passed with the package name no further options.

Pip provides a lot of options. I am especially interested in [`--index-url`](https://pip.pypa.io/en/stable/cli/pip_install/#cmdoption-0) and [`--extra-index-url`](https://pip.pypa.io/en/stable/cli/pip_install/#cmdoption-extra-index-url). These would allow us to install packages from non-standard package indexes, e.g., CPU-only builds of torch from [this index](https://download.pytorch.org/whl/torch_stable.html). It would also allow us to host our own internal package index, and install pip packages as osdeps from there.

To facilitate this, the osdeps syntax of pip packages would need to be extended, and the pip install command might need to be split up appropriately, to not leak the additional arguments to the installation of other packages.

An alternative to some of these use cases might be to define autobuild packages for these packages. But autobuild packages are currently not installed with pip, but with `python setup.py install` (related issue: https://github.com/rock-core/autobuild/issues/108), which might not work with some workspaces or packages. Also we would need to duplicate the dependencies of those packages in our package set then.

Any comments / suggestions?

**Comment by 2maz** [comment]
@moooeeeep 
> Pip provides a lot of options. I am especially interested in --index-url and --extra-index-url. These would allow us to install packages from non-standard package indexes, e.g., CPU-only builds of torch from this index. It would also allow us to host our own internal package index, and install pip packages as osdeps from there.

Did you look into setting up a workspace specific pip configuration, e.g. via pip config or via [PIP_CONFIG_FILE](https://pip.pypa.io/en/stable/topics/configuration/)  env variable. There you can set the extra-index-url without changing autoproj, although this will not be package specific.

Regarding the installation of python_package: 
You can have a look at a proof-of-concept that I started - check [autobuild](https://github.com/rock-core/autobuild/compare/master...2maz:autobuild:master) and [autoproj](https://github.com/rock-core/autoproj/compare/master...2maz:autoproj:master). Dependencies are loaded from setup.cfg or pyproject.toml files into autoproj.


@doudou 
> I am lucky and never had to dig into python package managers. Isn't there something standard closer to bundler, where you could list all the dependency requirements (including index URLs) and have them installed at once by the tool ?

You can already use "pip install -r requirements.txt", where requirements.txt is a collection of the commandline arguments including the list of packages - if that is what you are looking for. Maybe in combination with exporting a fixed dependency list via 'pip freeze'. 
Otherwise there is [conda](https://docs.conda.io/en/latest/) and there is [poetry](https://python-poetry.org/) as main players. But I hesitate to suggest integrating those with regard to maintainability inside autoproj.

**Comment by moooeeeep** [comment]
> Did you look into setting up a workspace specific pip configuration, e.g. via pip config or via [PIP_CONFIG_FILE](https://pip.pypa.io/en/stable/topics/configuration/) env variable. There you can set the extra-index-url without changing autoproj, although this will not be package specific.

Thanks for the hint - I didn't know that option existed! For a global `--extra-index-url` this seems workable.

I've seen a related discussion here, regarding passing certain options on a per-package basis (here: `--pre`): https://github.com/pypa/pip/issues/8426
This seems to be a hard problem in general. (Simply) installing the osdeps one after each other might not be as straight-forward as I thought.
